/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.auto.synch;

import static com.auto.synch.Hello_worldKt.executeMe;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        executeMe();
    }
}
